proyecto/MisCosas/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

from django.utils.translation import ugettext_lazy as _ #internacionalizacion



urlpatterns = [
    path('', views.index, name='index'),
    path('format=json', views.json, name='json'),
    path('format=xml', views.xml, name='xml'),
    path('alimentadores', views.alimentadores, name='alimentadores'),
    path('alimentadores/format=xml', views.xml_alimentadores, name='xml_alimentadores'),
    path('alimentadores/format=json', views.json_alimentadores, name='json_alimentadores'),
    path('descarga/<str:doc>', views.descarga, name='descarga'),
    path('descarga/<str:doc>/<str:id>', views.descarga_id, name='descarga_id'),
    path('descarga_com/<str:id>/<str:doc>', views.descarga_com, name='descarga_com'),
    path('eliminar/<str:id>', views.eliminar, name='eliminar'),
    path('estilo/<str:id>', views.estilo, name='estilo'),
    path('informacion', views.info, name='info'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('modify/<str:id>', views.modify, name='modyfy'),
    path('noticia/<str:id>', views.noticia, name='noticia'),
    path('registro/', views.registro, name='registro'),
    path('seleccionar/<str:id>', views.seleccionar, name='seleccionar'),
    path('subreddit/<str:id>', views.subreddit, name='subreddit'),
    path('subreddit/<str:id>/format=xml', views.xml_subreddit, name='xml_subreddit'),
    path('subreddit/<str:id>/format=json', views.json_subreddit, name='json_subreddit'),
    path('usuario/<str:id>', views.usuario, name='usuario'),
    path('usuarios/', views.usuarios, name='usuarios'),
    path('usuarios/format=xml', views.xml_usuarios, name='xml_usuarios'),
    path('usuarios/format=json', views.json_usuarios, name='json_usuarios'),
    path('video/<str:id>', views.video, name='video'),
    path('voto/<str:id>', views.voto, name='voto'),
    path('youtube/<str:id>', views.youtube, name='youtube'),
    path('youtube/<str:id>/format=xml', views.xml_youtube, name='xml_youtube'),
    path('youtube/<str:id>/format=json', views.json_youtube, name='json_youtube'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecto/proyecto/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.auth.views import LoginView as login

from django.conf.urls.i18n import i18n_patterns #internacionalizacion
from django.utils.translation import ugettext_lazy as _ #internacionalizacion

urlpatterns = [
    re_path(r'^i18n/', include('django.conf.urls.i18n')),#internacionalizacion
    path('admin/', admin.site.urls),
    path('login', login.as_view()),
    path('', include('MisCosas.urls')),
]

#
# urlpatterns += i18n_patterns('',
#     (_(r'^dual-lang/'), include('dualling.urls')),
#     (r'^', include('home.urls')),
# )

proyecto/MisCosas/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.


class Usuario(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    foto = models.ImageField(upload_to='usuarios/', blank=True)
    votos = models.IntegerField(default=0)
    comentarios = models.IntegerField(default=0)
    url = models.CharField(max_length=200)
    def __str__(self):
        return self.usuario.username


class Estilo(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    formato = models.CharField(max_length=10)
    tamano = models.CharField(max_length=10)
    estiloId = models.CharField(max_length=10)


class Alimentador(models.Model):
    nombre = models.CharField(max_length=200)
    titulo = models.CharField(max_length=200)
    enlace = models.CharField(max_length=200)
    alimentadorId = models.CharField(max_length=200)
    items = models.IntegerField()
    puntuacion = models.IntegerField(default=0)
    seleccionado = models.BooleanField(default=True)
    def __str__(self):
        return self.titulo

class Video(models.Model):
    alimentador = models.ForeignKey(Alimentador, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=200)
    url = models.CharField(max_length=200)
    videoId = models.CharField(max_length=200, default='')
    videoEmbed = models.TextField(blank=False)
    canal = models.CharField(max_length=200)
    link = models.CharField(max_length=200)
    descripcion = models.TextField(blank=False)
    puntuacion = models.IntegerField(default=0)
    def __str__(self):
        return self.titulo

class Noticia(models.Model):
    alimentador = models.ForeignKey(Alimentador, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=200)
    url = models.CharField(max_length=200)
    descripcion = models.CharField(max_length=200)
    subreddit = models.CharField(max_length=200)
    noticiaId = models.CharField(max_length=200)
    link = models.CharField(max_length=200)
    puntuacion = models.IntegerField(default=0)
    def __str__(self):
        return self.titulo

class Item(models.Model):
    item = models.CharField(max_length=200)
    noticia = models.ForeignKey(Noticia, on_delete=models.CASCADE, null=True)
    video = models.ForeignKey(Video, on_delete=models.CASCADE, null=True)
    titulo = models.CharField(max_length=200)
    url = models.CharField(max_length=200)
    itemId = models.CharField(max_length=10)
    puntuacion = models.IntegerField(default=0)
    positivos = models.IntegerField(default=0)
    negativos = models.IntegerField(default=0)
    def __str__(self):
        return self.titulo

class Voto(models.Model):
    item = models.CharField(max_length=10)
    noticia = models.ForeignKey(Noticia, on_delete=models.CASCADE, null=True)
    video = models.ForeignKey(Video, on_delete=models.CASCADE, null=True)
    alimentador = models.ForeignKey(Alimentador, on_delete=models.CASCADE)
    usuario = models.CharField(max_length=20)
    positivo = models.BooleanField(default=False)
    negativo = models.BooleanField(default=False)
    fecha = models.DateTimeField('publicado', default=timezone.now)
    def __str__(self):
        return self.usuario

class Comentario(models.Model):
    item = models.CharField(max_length=10)
    noticia = models.ForeignKey(Noticia, on_delete=models.CASCADE, null=True)
    video = models.ForeignKey(Video, on_delete=models.CASCADE, null=True)
    usuario = models.CharField(max_length=200)
    titulo = models.CharField(max_length=200)
    cuerpo = models.CharField(max_length=256)
    miniatura = models.ImageField(upload_to='comentarios/', blank=True)
    fecha = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.titulo

proyecto/MisCosas/forms.py
from django import forms

from .models import Estilo

format = [('Oscuro', 'Oscuro'), ('Ligero', 'Ligero')]

size = [('Reducido', 'Reducido'), ('Normal', 'Normal'), ('Ampliado', 'Ampliado')]


class ComentarioForm(forms.Form):
    titulo = forms.CharField(max_length=200)
    cuerpo = forms.CharField(max_length=200)
    miniatura = forms.ImageField(required=False)

class FotoUsuarioForm(forms.Form):
    foto = forms.ImageField(required=False)

class EstiloForm(forms.Form):
    formato = forms.ChoiceField(choices=format)
    tamano = forms.ChoiceField(choices=size)

class YoutubeForm(forms.Form):
    Identificador = forms.CharField(max_length=50)

class SubredditForm(forms.Form):
    Nombre = forms.CharField(max_length=50)

proyecto/MisCosas/views.py
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from xml.sax.handler import ContentHandler
from .models import Video, Voto, Comentario, Alimentador, Noticia, Item, Usuario, Estilo
from .apps import xmlStream
from .forms import ComentarioForm, FotoUsuarioForm, EstiloForm, YoutubeForm, SubredditForm
from . import ytparser
from. import rdparser

import mimetypes
import urllib.request
import sys
import operator



def get_estilo(request):
    if request.user.is_authenticated:
        try:
            try:
                u = Usuario.objects.get(usuario=request.user)
                estiloId = Estilo.objects.get(usuario=u).estiloId
            except Usuario.DoesNotExist: # el admin no está en la base de datos de Usuarios
                estiloId = 'sinEstilo'
        except Estilo.DoesNotExist: # si el usuario no tiene estilo predefinido
            estiloId = 'sinEstilo'
    else: # si no hay usuario autenticado
        estiloId = 'sinEstilo'
    return estiloId



# Create your views here.

@csrf_exempt
def login_view(request):
    if request.method == 'POST':
        username = request.POST['user']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
        return redirect(request.POST['origen'])
    else:
        return render(request, 'MisCosas/invalid.html', {}, status=404)



@csrf_exempt
def logout_view(request):
    logout(request)
    return redirect(request.POST['origen'])



@csrf_exempt
def registro(request):
    if request.method == "GET":
        context = {'registrado': False}
        return render(request, 'MisCosas/form_registro.html', context)
    elif request.method == "POST":
        username = request.POST['usuario']
        password = request.POST['contraseña']
        email = request.POST['email']
        try:
            user = User.objects.create_user(username, email, password)
            usuario = Usuario(usuario=user, url='http://localhost:8000/MisCosas/usuario/' + username)
            if request.FILES:
                usuario.foto = request.FILES['foto']
            usuario.save()
            context = {'registrado': True}
        except IntegrityError:
            context = {'registrado': False, 'error': True}
        return render(request, 'MisCosas/form_registro.html', context)
    else:
        return render(request, 'MisCosas/invalid.html', {}, status=404)



def index(request):
    if request.method == 'GET':
        items_diez = Item.objects.annotate(punt=Count('puntuacion')).order_by('-puntuacion')[:10]
        items_cinco = Voto.objects.filter(usuario=request.user.username).annotate(f=Count('fecha')).order_by('-fecha')[:5]
        alimentadores = Alimentador.objects.filter(seleccionado=True)
        estiloId = get_estilo(request)
        context = {'alimentadores': alimentadores, 'items_diez': items_diez, 'items_cinco': items_cinco, 'estiloId': estiloId,
                    'formYt': YoutubeForm, 'formSd': SubredditForm}
        return render(request, 'MisCosas/indexApp.html', context, status=200)
    else:
        return render(request, idioma + 'MisCosas/invalid.html', {}, status=404)



def xml(request):
    if request.method == 'GET':
        items_diez = Item.objects.annotate(punt=Count('puntuacion')).order_by('-puntuacion')[:10]
        items_cinco = Voto.objects.filter(usuario=request.user.username).annotate(f=Count('fecha')).order_by('-fecha')[:5]
        alimentadores = Alimentador.objects.all()
        context = {'alimentadores': alimentadores, 'items_diez': items_diez, 'items_cinco': items_cinco, 'user': request.user}
        return render(request, 'MisCosas/indexApp.xml', context, content_type='text/xml')
    else:
        return render(request, 'MisCosas/invalid.html', {}, status=404)


def json(request):
    if request.method == 'GET':
        items_diez = Item.objects.annotate(punt=Count('puntuacion')).order_by('-puntuacion')[:10]
        items_cinco = Voto.objects.filter(usuario=request.user.username).annotate(f=Count('fecha')).order_by('-fecha')[:5]
        alimentadores = Alimentador.objects.filter(seleccionado=True)
        context = {'alimentadores': alimentadores, 'items_diez': items_diez, 'items_cinco': items_cinco, 'user': request.user}
        return render(request, 'MisCosas/indexApp.json', context, content_type='application/json')
    else:
        return render(request, 'MisCosas/invalid.html', {}, status=404)


def descarga(request, doc):
    if request.method == 'GET':
        fl_path = 'MisCosas/' + doc
        filename = doc
        mime_type, _ = mimetypes.guess_type(fl_path)
        if doc == 'indexApp.xml' or doc == 'indexApp.json':
            items_diez =  Item.objects.annotate(punt=Count('puntuacion')).order_by('-puntuacion')[:10]
            items_cinco = Voto.objects.filter(usuario=request.user.username).annotate(f=Count('fecha')).order_by('-fecha')[:5]
            alimentadores = Alimentador.objects.filter(seleccionado=True)
            context = {'alimentadores': alimentadores, 'items_diez': items_diez, 'items_cinco': items_cinco, 'user': request.user}
        elif doc == 'indexAlimentadores.xml' or doc == 'indexAlimentadores.json':
            alimentadores = Alimentador.objects.all()
            context = {'feeders': alimentadores}
        elif doc == 'usuarios.xml' or doc == 'usuarios.json':
            usuarios = Usuario.objects.all()
            context = {'users': usuarios}
        response = render(request, fl_path, context, content_type=mime_type)
        response['Content-Disposition'] = "attachment; filename=%s" % filename
        return response
    else:
        return render(request, 'MisCosas/invalid.html', {}, status=404)



def descarga_id(request, doc, id):
    if request.method == 'GET':
        fl_path = 'MisCosas/' + doc
        filename = doc
        mime_type, _ = mimetypes.guess_type(fl_path)
        if doc == 'youtube.xml' or doc == 'youtube.json':
            items = Video.objects.filter(alimentador=Alimentador.objects.get(alimentadorId=id))
            context = {'items': items}
        elif doc == 'subreddit.xml' or doc == 'subreddit.json':
            items = Noticia.objects.filter(alimentador=Alimentador.objects.get(alimentadorId=id))
            context = {'items': items}
        else:
            return render(request, 'MisCosas/invalid.html', {}, status=404)
        response = render(request, fl_path, context, content_type=mime_type)
        response['Content-Disposition'] = "attachment; filename=%s" % filename
        return response
    else:
        return render(request, 'MisCosas/invalid.html', {}, status=404)



def descarga_com(request, id, doc):
    if request.method == 'GET':
        fl_path = 'MisCosas/' + doc
        filename = doc
        mime_type, _ = mimetypes.guess_type(fl_path)
        try:
            comentarios = Comentario.objects.filter(video=Video.objects.get(videoId=id))
            item = Video.objects.get(videoId=id)
        except Video.DoesNotExist:
            comentarios = Comentario.objects.filter(noticia=Noticia.objects.get(noticiaId=id))
            item = Noticia.objects.get(noticiaId=id)
        context = {'comments': comentarios, 'item': item}
        response = render(request, fl_path, context, content_type=mime_type)
        response['Content-Disposition'] = "attachment; filename=%s" % filename
        return response
    else:
        return render(request, 'MisCosas/invalid.html', {}, status=404)




def alimentadores(request):
    if request.method == 'GET':
        alimentadores = Alimentador.objects.all()
        estiloId = get_estilo(request)
        context = {'alimentadores': alimentadores, 'estiloId': estiloId}
        return render(request, 'MisCosas/indexAlimentadores.html', context)
    else:
        return render(request, 'MisCosas/invalid.html', {}, status=404)



def xml_alimentadores(request):
    if request.method == 'GET':
        alimentadores = Alimentador.objects.all()
        context = {'feeders': alimentadores}
        return render(request, 'MisCosas/indexAlimentadores.xml', context, content_type='text/xml')
    else:
        return render(request, 'MisCosas/invalid.html', {}, status=404)



def json_alimentadores(request):
    if request.method == 'GET':
        alimentadores = Alimentador.objects.all()
        context = {'feeders': alimentadores}
        return render(request, 'MisCosas/indexAlimentadores.json', context, content_type='application/json')
    else:
        return render(request, 'MisCosas/invalid.html', {}, status=404)



def eliminar(request, id):
    if request.method == 'POST':
        try:
            a = Alimentador.objects.get(alimentadorId=id)
            a.seleccionado = False
            a.save()
            if request.POST['origen'] == 'index':
                return redirect('index')
            else:
                return redirect(request.POST['origen'], id)
        except Alimentador.DoesNotExist:
            context = {'recurso': 'Alimentador'}
            return render(request, 'MisCosas/error.html', context, status=404)
    else:
        return render(request, 'MisCosas/invalid.html', {}, status=404)



def seleccionar(request, id):
    if request.method == 'POST':
        try:
            a = Alimentador.objects.get(alimentadorId=id)
            if a.nombre == 'youtube':
                url = 'https://www.youtube.com/feeds/videos.xml?channel_id=' + id
                xmlStream = urllib.request.urlopen(url)
                ytparser.Parser.parse(xmlStream)
            else:
                rdId = id + '.rss'
                url = 'https://www.reddit.com/r/' + rdId
                xmlStream = urllib.request.urlopen(url)

proyecto/MisCosas/templates/MisCosas/base.html
{% load static %}
{% load i18n %}
<html>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel='shortcut icon' href='/static/MisCosas/icon.ico'>
        <!-- Main CSS -->
        <link rel="stylesheet" type='text/css' href="/static/MisCosas/main.css">
        <title>MisCosasWeb</title>
    </head>
    <body id={{ estiloId }}>
        <div id=inicio>
            <div id='titulo'>
                MisCosas
            </div>
            <div id="banner">
                <img src="/static/MisCosas/banner.png" class="banner" />
            </div>
            <div id='navegacion'>
                <ul class="nav nav-pills">
                    {% if request.path != '/' %}
                        <li class="nav-item">
                            <a class="nav-link active" href='/'>{% trans 'Inicio' %}</a>
                        </li>
                    {% endif %}
                    {% if request.path != '/alimentadores' %}
                        <li class="nav-item">
                            <a class="nav-link active" href="/alimentadores">{% trans 'Alimentadores' %}</a>
                        </li>
                    {% endif %}
                    {% if request.path != '/usuarios/' %}
                        <li class="nav-item">
                            <a class="nav-link" href="/usuarios">{% trans 'Usuarios' %}</a>
                        </li>
                    {% endif %}
                    {% if request.path != '/informacion' %}
                        <li class="nav-item">
                            <a class="nav-link" href="/informacion">{% trans 'Información' %}</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
            <div id='form_login'>
                {% if user.is_authenticated %}
                    <p><b> {{ user.username }}</b>
                    <form method="post" action="/logout/">{% csrf_token %}
                        <input type="hidden" name="origen" value={{ request.path }}><br>
                        <input type="submit" value="Logout">
                    </form>
                {% else %}
                    <form method="post" action="/login/">{% csrf_token %}
                        <input type="hidden" name="origen" value={{ request.path }}><br>
                        <label for="user">{% trans 'Usuario:' %}</label>
                        <input type="text" name="user"><br>
                        <label for="password">{% trans 'Contraseña:' %} </label>
                        <input type="password" name="password"><br>
                        <input type="submit" value="Login"> o <a href="/registro/"> Registrar cuenta </a>
                    </form>
                {% endif %}
            </div>
            <div id='idioma'>
                <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
                    {% trans 'Idioma:' %}
                    <input name="next" type="hidden" value="{{ redirect_to }}">
                    <select name="language">
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}
                        {% for language in languages %}
                            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                                {{ language.name_local }} ({{ language.code }})
                            </option>
                        {% endfor %}
                    </select>
                    <input type="submit" value="Go">
                </form>
            </div>
        </div>
        {% block contenido %}
        {% endblock %}
        <div id=pie_pagina>
            <footer>
                {% trans 'Esta aplicación utiliza datos proporcionados por ' %}<a class='link' href='https://www.youtube.com/'>YouTube</a>, <a class='link' href='https://www.reddit.com/'>Reddit</a>.
            </footer>
        </div>
    </body>
</html>

proyecto/MisCosas/templates/MisCosas/form_registro.html
{% extends 'MisCosas/base.html' %}
    {% load i18n %}
    {% block contenido %}
        <h2>{% trans 'Página de registro de usuario' %}</h2>
        <title>{% trans 'Registrar cuenta' %}</title>
        {% if registrado %}
            {% trans 'Te has registrado correctamente en MisCosas. Ya puedes hacer' %} <a href='/'>{% trans 'login' %}</a>.
        {% else %}
            {% if error %}
                {% trans 'Este nombre ya está en uso. Prueba con otro diferente.' %}
            {% endif %}
            <form method="POST" action="/registro/" enctype='multipart/form-data'>{% csrf_token %}
                <label for="usuario">{% trans 'Usuario:' %} </label>
                <input id = "usr" type="text" name="usuario"><br>
                <label for="contraseña">{% trans 'Contraseña:' %} </label>
                <input id = "psw" type="password" name="contraseña"><br>
                <label for="email">{% trans 'Email:' %} </label>
                <input id = "eml" type="text" name="email"><br>
                <label for="picture">{% trans 'Selecciona una foto:' %}</label>
                <input type="file" name="foto" class='foto' accept=".pdf,.jpg,.png" multiple>
                <!-- <input type="image" name="foto" accept=".pdf,.jpg,.png" multiple> -->
                <input type="submit" value="Registrar">
            </form>
        {% endif %}
    {% endblock %}

proyecto/MisCosas/templates/MisCosas/index.html
{% extends 'MisCosas/base.html' %}
    {% block contenido %}
        <html lang="es">
            <body>
                <h1>Listado de vídeos del canal</h1>
                {% for video in videos %}
                    <ul>
                    <li><a href= {{ video.url }}>{{ video.titulo }}:</a>
                    {% if user.is_authenticated %}
                        {% for voto in video.voto_set.all %}
                            {% if voto.usuario == request.user.username and voto.positivo %}
                                <button id='boton' type='button' formmethod='POST' action='like'><a href='{% url 'like' id=video.videoId %}'>Me Gusta</span></a></button>
                                <button type='button' formmethod='POST' action='dislike'><a href='{% url 'dislike' id=video.videoId %}'>No me Gusta</span></a></button>
                                {{ break }}{{ break }}
                            {% elif voto.usuario == request.user.username and voto.negativo %}
                                <button type='button' formmethod='POST' action='like'><a href='{% url 'like' id=video.videoId %}'>Me Gusta</span></a></button>
                                <button id='boton' type='button' formmethod='POST' action='dislike'><a href='{% url 'dislike' id=video.videoId %}'>No me Gusta</span></a></button>
                                <br>
                                {% else %}
                                <button type='button' class='boton btn-light' formmethod='POST' action='like'><a href='{% url 'like' id=video.videoId %}'>Me Gusta</span></a></button>
                                <button type='button' class='boton btn-light' formmethod='POST' action='dislike'><a href='{% url 'dislike' id=video.videoId %}'>No me Gusta</span></a></button>
                                <br>
                            {% endif %}
                        {% endfor %}
                        {{votos.usuario_set.all}}
                        {% if not request.user.username in votos.usuario_set.all or not video.voto_set.all %}
                            <button type='button' class='boton btn-light' formmethod='POST' action='like'><a href='{% url 'like' id=video.videoId %}'>Me Gusta</span></a></button>
                            <button type='button' class='boton btn-light' formmethod='POST' action='dislike'><a href='{% url 'dislike' id=video.videoId %}'>No me Gusta</span></a></button>
                        {% endif %}
                    {% endif %}
                    <br>
                    <a href= http://localhost:8000/MisCosas/video/{{ video.videoId }}>http://localhost:8000/MisCosas/video/{{ video.videoId }}</a>
                    <p>Puntuación: {{ video.puntuacion }}.</p>
                    </li>
                    </ul>
                {% endfor %}
            </body>
        </html>
    {% endblock %}

proyecto/MisCosas/templates/MisCosas/indexAlimentadores.html
{% extends 'MisCosas/base.html' %}
    {% load i18n %}
    {% block contenido %}
        <html lang="es">
            <body>
                <br><br>
                <a href="/descarga/indexAlimentadores.xml" download="indexAlimentadores.xml">{% trans 'Descarga el canal RSS en XML' %}</a>
                <a href="/descarga/indexAlimentadores.json" download="indexAlimentadores.json">{% trans 'Descarga el canal RSS en JSON' %}</a>
                <h2>{% trans 'Alimentadores que ha servido MisCosas' %}</h2>
                <ul>
                {% for alimentador in alimentadores %}
                    <li>
                        <p><a href='{% url alimentador.nombre id=alimentador.alimentadorId %}'>{{ alimentador.titulo }}</a><br>
                           <a href={{ alimentador.enlace }}>{{ alimentador.enlace }}</a><br>
                           {% trans 'Hay ' %}{{ alimentador.items }}{% trans ' items disponibles' %}.<br>
                           {% trans 'Ha obtenido un total de ' %}{{ alimentador.puntuacion }}{% trans ' puntos' %}.
                        </p>
                    </li>
                {% endfor %}
                </ul>
            </body>
        </html>
    {% endblock %}

proyecto/MisCosas/templates/MisCosas/invalid.html
{% extends 'MisCosas/base.html' %}
    {% load i18n %}
    {% block contenido %}
        <html lang="es">
            <body>
                <h2>{% trans 'Recurso no encontrado, introduca un nombre válido.' %}</h2>
                <br>
                <br>
                <br>
                <br>
            </body>
        </html>
    {% endblock %}

proyecto/MisCosas/templates/MisCosas/login_form.html
<form action="action_page.php" method="post">
 <div class="imgcontainer">
   <img src="img_avatar2.png" alt="Avatar" class="avatar">
 </div>

 <div class="container">
   <label for="uname"><b>Username</b></label>
   <input type="text" placeholder="Enter Username" name="uname" required>

   <label for="psw"><b>Password</b></label>
   <input type="password" placeholder="Enter Password" name="psw" required>

   <button type="submit">Login</button>
   <label>
     <input type="checkbox" checked="checked" name="remember"> Remember me
   </label>
 </div>

 <div class="container" style="background-color:#f1f1f1">
   <button type="button" class="cancelbtn">Cancel</button>
   <span class="psw">Forgot <a href="#">password?</a></span>
 </div>
</form> 

proyecto/MisCosas/templates/MisCosas/redirect.html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta http-equiv="refresh" content="0;URL=http://localhost:8000/MisCosas"/>
    </head>
</html>

proyecto/MisCosas/templates/MisCosas/usuarios.html
{% extends 'MisCosas/base.html' %}
    {% load i18n %}
    {% block contenido %}
        {% load static %}
        <br><br>
        <a href="/descarga/usuarios.xml" download="usuarios.xml">{% trans 'Descarga el canal RSS en XML' %}</a>
        <a href="/descarga/usuarios.json" download="usuarios.json">{% trans 'Descarga el canal RSS en JSON' %}</a>
        <h2>{% trans 'Usuarios de MisCosas' %}</h2>
        {% if usuarios %}
            {% for usuario in usuarios %}
                <div id='texto_foto'>
                    <h4>{{ usuario.usuario.username }}</h4>
                    {% trans 'Total items votados: ' %}{{ usuario.votos }}<br>
                    {% trans 'Total items comentados: ' %}{{ usuario.comentarios }}<br>
                    {% trans 'Accede a la información del usuario ' %}<a href='{% url 'usuario' id=usuario.usuario.username %}'>{% trans 'aquí' %}</a>.
                </div>
                <br><br>
                {% if usuario.foto %}
                    <img id='imagen' src='{% static '' %}{{usuario.foto}}'><br>
                    <!-- <img src='/media/{{ usuario.foto }}'><br> -->
                {% else %}
                    <img id='imagen' src='{% static '' %}usuarios/default.png'><br>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endblock %}